sonar.organization=umahanish
sonar.projectKey=umahanish_hms-application
sonar.projectName=hms-application

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=backend/tests/**,frontend/src/**/*.test.jsx,frontend/src/**/*.test.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/build/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
